name: C++ Tests

on:
  push:
    paths: ['CMakeLists.txt', 'include/**', 'lib/**', 'tests/**', '.github/workflows/ctest.yml']
  pull_request:
    paths: ['CMakeLists.txt', 'include/**', 'lib/**', 'tests/**', '.github/workflows/ctest.yml']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup CMake, GCC / Clang and Make
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make

    # Setup GTest
    - name: Install Google Test
      run: sudo apt-get install -y libgtest-dev

    # Build project
    - name: Configure CMake
      run: cmake -S . -B build/
    - name: Build
      run: cmake --build build/ --target all

    # Run GTest tests
    - name: Test
      working-directory: build/
      run: ctest
